/*
 * LDAP Chai API
 * Copyright (c) 2006-2009 Novell, Inc.
 * Copyright (c) 2009-2010 The LDAP Chai Project
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.novell.ldapchai.exception;

class EdirErrorMap implements ErrorMap {

    public ChaiErrorCode errorForMessage(final String message)
    {
        return forMessage(message).chaiErrorCode;
    }

    public boolean isPermenant(final String message) {
        return forMessage(message).isPermenant();
    }

    public boolean isAuthenticationRelated(final String message) {
        return forMessage(message).isAuthentication();
    }

    private static EdirError forMessage(final String message) {
        if (message == null || message.length() < 1) {
            return EdirError.UNKNOWN;
        }

        for (final EdirError error : EdirError.values()) {
            if (message.contains(String.valueOf(error.getErrorCodeNumber()))) {
                return error;
            }

            for (final String errorString : error.getErrorStrings()) {
                if (message.contains(String.valueOf(errorString))) {
                    return error;
                }
            }
        }

        return EdirError.UNKNOWN;
    }

    enum EdirError {
        UNKNOWN                                        (-1,   ChaiErrorCode.UNKNOWN,                       true, false),
        BUFFER_TOO_SMALL                               (-119, ChaiErrorCode.UNKNOWN,                       true, false),
        VOLUME_FLAG_NOT_SET                            (-120, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_ITEMS_FOUND                                 (-121, ChaiErrorCode.UNKNOWN,                       true, false),
        CONN_ALREADY_TEMPORARY                         (-122, ChaiErrorCode.UNKNOWN,                       true, false),
        CONN_ALREADY_LOGGED_IN                         (-123, ChaiErrorCode.UNKNOWN,                       true, false),
        CONN_NOT_AUTHENTICATED                         (-124, ChaiErrorCode.UNKNOWN,                       true, false),
        CONN_NOT_LOGGED_IN                             (-125, ChaiErrorCode.UNKNOWN,                       true, false),
        NCP_BOUNDARY_CHECK_FAILED                      (-126, ChaiErrorCode.UNKNOWN,                       true, false),
        LOCK_WAITING                                   (-127, ChaiErrorCode.UNKNOWN,                       true, false),
        LOCK_FAIL                                      (-128, ChaiErrorCode.UNKNOWN,                       true, false),
        OUT_OF_HANDLES                                 (-129, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_OPEN_PRIVILEGE                              (-130, ChaiErrorCode.UNKNOWN,                       true, false),
        HARD_IO_ERROR                                  (-131, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_CREATE_PRIVILEGE                            (-132, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_CREATE_DELETE_PRIV                          (-133, ChaiErrorCode.UNKNOWN,                       true, false),
        R_O_CREATE_FILE                                (-134, ChaiErrorCode.UNKNOWN,                       true, false),
        CREATE_FILE_INVALID_NAME                       (-135, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_FILE_HANDLE                            (-136, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SEARCH_PRIVILEGE                            (-137, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_DELETE_PRIVILEGE                            (-138, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_RENAME_PRIVILEGE                            (-139, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SET_PRIVILEGE                               (-140, ChaiErrorCode.UNKNOWN,                       true, false),
        SOME_FILES_IN_USE                              (-141, ChaiErrorCode.UNKNOWN,                       true, false),
        ALL_FILES_IN_USE                               (-142, ChaiErrorCode.UNKNOWN,                       true, false),
        SOME_READ_ONLY                                 (-143, ChaiErrorCode.UNKNOWN,                       true, false),
        ALL_READ_ONLY                                  (-144, ChaiErrorCode.UNKNOWN,                       true, false),
        SOME_NAMES_EXIST                               (-145, ChaiErrorCode.UNKNOWN,                       true, false),
        ALL_NAMES_EXIST                                (-146, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_READ_PRIVILEGE                              (-147, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_WRITE_PRIVILEGE                             (-148, ChaiErrorCode.UNKNOWN,                       true, false),
        FILE_DETACHED                                  (-149, ChaiErrorCode.UNKNOWN,                       true, false),
        INSUFFICIENT_MEMORY                            (-150, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_ALLOC_SPACE                                 (-150, ChaiErrorCode.UNKNOWN,                       true, false),
        TARGET_NOT_A_SUBDIR                            (-150, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SPOOL_SPACE                                 (-151, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_VOLUME                                 (-152, ChaiErrorCode.UNKNOWN,                       true, false),
        DIRECTORY_FULL                                 (-153, ChaiErrorCode.UNKNOWN,                       true, false),
        RENAME_ACROSS_VOLUME                           (-154, ChaiErrorCode.UNKNOWN,                       true, false),
        BAD_DIR_HANDLE                                 (-155, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_PATH                                   (-156, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SUCH_EXTENSION                              (-156, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_DIR_HANDLES                                 (-157, ChaiErrorCode.UNKNOWN,                       true, false),
        BAD_FILE_NAME                                  (-158, ChaiErrorCode.UNKNOWN,                       true, false),
        DIRECTORY_ACTIVE                               (-159, ChaiErrorCode.UNKNOWN,                       true, false),
        DIRECTORY_NOT_EMPTY                            (-160, ChaiErrorCode.UNKNOWN,                       true, false),
        DIRECTORY_IO_ERROR                             (-161, ChaiErrorCode.UNKNOWN,                       true, false),
        IO_LOCKED                                      (-162, ChaiErrorCode.UNKNOWN,                       true, false),
        TRANSACTION_RESTARTED                          (-163, ChaiErrorCode.UNKNOWN,                       true, false),
        RENAME_DIR_INVALID                             (-164, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_OPENCREATE_MODE                        (-165, ChaiErrorCode.UNKNOWN,                       true, false),
        ALREADY_IN_USE                                 (-166, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_RESOURCE_TAG                           (-167, ChaiErrorCode.UNKNOWN,                       true, false),
        ACCESS_DENIED                                  (-168, ChaiErrorCode.UNKNOWN,                       true, false),
        DSERR_LOGIN_SIGNING_REQUIRED                   (-188, ChaiErrorCode.UNKNOWN,                       true, false),
        DSERR_LOGIN_ENCRYPT_REQUIRED                   (-189, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_DATA_STREAM                            (-190, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_NAME_SPACE                             (-191, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_ACCOUNTING_PRIVILEGES                       (-192, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_ACCOUNT_BALANCE                             (-193, ChaiErrorCode.UNKNOWN,                       true, false),
        CREDIT_LIMIT_EXCEEDED                          (-194, ChaiErrorCode.UNKNOWN,                       true, false),
        TOO_MANY_HOLDS                                 (-195, ChaiErrorCode.UNKNOWN,                       true, false),
        ACCOUNTING_DISABLED                            (-196, ChaiErrorCode.UNKNOWN,                       true, false),
        LOGIN_LOCKOUT                                  (-197, ChaiErrorCode.UNKNOWN,                       true, true),
        NO_CONSOLE_RIGHTS                              (-198, ChaiErrorCode.UNKNOWN,                       true, false),
        Q_IO_FAILURE                                   (-208, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_QUEUE                                       (-209, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_Q_SERVER                                    (-210, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_Q_RIGHTS                                    (-211, ChaiErrorCode.UNKNOWN,                       true, false),
        Q_FULL                                         (-212, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_Q_JOB                                       (-213, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_Q_JOB_RIGHTS                                (-214, ChaiErrorCode.UNKNOWN,                       true, false),
        UNENCRYPTED_NOT_ALLOWED                        (-214, ChaiErrorCode.UNKNOWN,                       true, false),
        DUPLICATE_PASSWORD                             (-215, ChaiErrorCode.DUPLICATE_PASSWORD,            true, false),
        Q_IN_SERVICE                                   (-215, ChaiErrorCode.UNKNOWN,                       true, false),
        Q_NOT_ACTIVE                                   (-216, ChaiErrorCode.UNKNOWN,                       true, false),
        PASSWORD_TOO_SHORT                             (-216, ChaiErrorCode.PASSWORD_TOO_SHORT,            true, false),
        MAXIMUM_LOGINS_EXCEEDED                        (-217, ChaiErrorCode.UNKNOWN,                       true, false),
        Q_STN_NOT_SERVER                               (-217, ChaiErrorCode.UNKNOWN,                       true, false),
        BAD_LOGIN_TIME                                 (-218, ChaiErrorCode.UNKNOWN,                       true, false),
        Q_HALTED                                       (-218, ChaiErrorCode.UNKNOWN,                       true, false),
        NODE_ADDRESS_VIOLATION                         (-219, ChaiErrorCode.UNKNOWN,                       true, false),
        Q_MAX_SERVERS                                  (-219, ChaiErrorCode.UNKNOWN,                       true, false),
        LOG_ACCOUNT_EXPIRED                            (-220, ChaiErrorCode.UNKNOWN,                       true, true),
        BAD_PASSWORD                                   (-222, ChaiErrorCode.BAD_PASSWORD,                  true, true),
        PASSWORD_EXPIRED                               (-223, ChaiErrorCode.PASSWORD_EXPIRED,              true, true),
        NO_LOGIN_CONN_AVAILABLE                        (-224, ChaiErrorCode.UNKNOWN,                       true, false),
        WRITE_TO_GROUP_PROPERTY                        (-232, ChaiErrorCode.UNKNOWN,                       true, false),
        MEMBER_ALREADY_EXISTS                          (-233, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SUCH_MEMBER                                 (-234, ChaiErrorCode.UNKNOWN,                       true, false),
        PROPERTY_NOT_GROUP                             (-235, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SUCH_VALUE_SET                              (-236, ChaiErrorCode.UNKNOWN,                       true, false),
        PROPERTY_ALREADY_EXISTS                        (-237, ChaiErrorCode.UNKNOWN,                       true, false),
        OBJECT_ALREADY_EXISTS                          (-238, ChaiErrorCode.UNKNOWN,                       true, false),
        ILLEGAL_NAME                                   (-239, ChaiErrorCode.UNKNOWN,                       true, false),
        ILLEGAL_WILDCARD                               (-240, ChaiErrorCode.UNKNOWN,                       true, false),
        BINDERY_SECURITY                               (-241, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_OBJECT_READ_RIGHTS                          (-242, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_OBJECT_RENAME_RIGHTS                        (-243, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_OBJECT_DELETE_RIGHTS                        (-244, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_OBJECT_CREATE_RIGHTS                        (-245, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_PROPERTY_DELETE_RIGHTS                      (-246, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_PROPERTY_CREATE_RIGHTS                      (-247, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_PROPERTY_WRITE_RIGHTS                       (-248, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_PROPERTY_READ_RIGHTS                        (-249, ChaiErrorCode.UNKNOWN,                       true, false),
        TEMP_REMAP                                     (-250, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SUCH_PROPERTY                               (-251, ChaiErrorCode.UNKNOWN,                       true, false),
        UNKNOWN_REQUEST                                (-251, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SUCH_OBJECT                                 (-252, ChaiErrorCode.NO_SUCH_OBJECT,                true, false),
        MESSAGE_QUEUE_FULL                             (-252, ChaiErrorCode.UNKNOWN,                       true, false),
        TARGET_ALREADY_HAS_MSG                         (-252, ChaiErrorCode.UNKNOWN,                       true, false),
        BAD_STATION_NUMBER                             (-253, ChaiErrorCode.UNKNOWN,                       true, false),
        BINDERY_LOCKED                                 (-254, ChaiErrorCode.UNKNOWN,                       true, false),
        DIR_LOCKED                                     (-254, ChaiErrorCode.UNKNOWN,                       true, false),
        DSERR_TIMEOUT                                  (-254, ChaiErrorCode.UNKNOWN,                       true, false),
        LOGIN_DISABLED                                 (-254, ChaiErrorCode.UNKNOWN,                       true, false),
        SPOOL_DELETE                                   (-254, ChaiErrorCode.UNKNOWN,                       true, false),
        TRUSTEE_NOT_FOUND                              (-254, ChaiErrorCode.UNKNOWN,                       true, false),
        BAD_PARAMETER                                  (-255, ChaiErrorCode.UNKNOWN,                       true, false),
        BAD_SPOOL_PRINTER                              (-255, ChaiErrorCode.UNKNOWN,                       true, false),
        CLOSE_FCB                                      (-255, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_OF_SOME_SORT                               (-255, ChaiErrorCode.UNKNOWN,                       true, false),
        FILE_EXISTS                                    (-255, ChaiErrorCode.UNKNOWN,                       true, false),
        FILE_NAME                                      (-255, ChaiErrorCode.UNKNOWN,                       true, false),
        HARD_FAILURE                                   (-255, ChaiErrorCode.UNKNOWN,                       true, false),
        IO_BOUND                                       (-255, ChaiErrorCode.UNKNOWN,                       true, false),
        MUST_FORCE_DOWN                                (-255, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_FILES_FOUND                                 (-255, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SPOOL_FILE                                  (-255, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_TRUSTEE_CHANGE_PRIV                         (-255, ChaiErrorCode.UNKNOWN,                       true, false),
        TARGET_NOT_ACCEPTING_MSGS                      (-255, ChaiErrorCode.UNKNOWN,                       true, false),
        TARGET_NOT_LOGGED_IN                           (-255, ChaiErrorCode.UNKNOWN,                       true, false),
        PREEMPT_COMM                                   (-286, ChaiErrorCode.UNKNOWN,                       true, false),
        CLOSE_COMM                                     (-287, ChaiErrorCode.UNKNOWN,                       true, false),
        OPEN_COMM                                      (-288, ChaiErrorCode.UNKNOWN,                       true, false),
        ALREADY_EXISTS                                 (-289, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_COUNT                                  (-290, ChaiErrorCode.UNKNOWN,                       true, false),
        TIMEOUT                                        (-291, ChaiErrorCode.UNKNOWN,                       true, false),
        FATAL                                          (-292, ChaiErrorCode.UNKNOWN,                       true, false),
        MEMORY_ERR                                     (-293, ChaiErrorCode.UNKNOWN,                       true, false),
        VRDRIVER_INTERFACE_MISMATCH                    (-294, ChaiErrorCode.UNKNOWN,                       true, false),
        VRDRIVER_CREATE_FAIL                           (-295, ChaiErrorCode.UNKNOWN,                       true, false),
        VRDRIVER_MISSING                               (-296, ChaiErrorCode.UNKNOWN,                       true, false),
        JVM_CREATE_FAIL                                (-297, ChaiErrorCode.UNKNOWN,                       true, false),
        JVM_INIT_FAIL                                  (-298, ChaiErrorCode.UNKNOWN,                       true, false),
        JRE_LOAD_FAIL                                  (-299, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_JRE                                         (-300, ChaiErrorCode.UNKNOWN,                       true, false),
        NOT_ENOUGH_MEMORY                              (-301, ChaiErrorCode.UNKNOWN,                       true, false),
        BAD_KEY                                        (-302, ChaiErrorCode.UNKNOWN,                       true, false),
        BAD_CONTEXT                                    (-303, ChaiErrorCode.UNKNOWN,                       true, false),
        BUFFER_FULL                                    (-304, ChaiErrorCode.UNKNOWN,                       true, false),
        LIST_EMPTY                                     (-305, ChaiErrorCode.UNKNOWN,                       true, false),
        BAD_SYNTAX                                     (-306, ChaiErrorCode.UNKNOWN,                       true, false),
        BUFFER_EMPTY                                   (-307, ChaiErrorCode.UNKNOWN,                       true, false),
        BAD_VERB                                       (-308, ChaiErrorCode.UNKNOWN,                       true, false),
        EXPECTED_IDENTIFIER                            (-309, ChaiErrorCode.UNKNOWN,                       true, false),
        EXPECTED_EQUALS                                (-310, ChaiErrorCode.UNKNOWN,                       true, false),
        ATTR_TYPE_EXPECTED                             (-311, ChaiErrorCode.UNKNOWN,                       true, false),
        ATTR_TYPE_NOT_EXPECTED                         (-312, ChaiErrorCode.UNKNOWN,                       true, false),
        FILTER_TREE_EMPTY                              (-313, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_OBJECT_NAME                            (-314, ChaiErrorCode.UNKNOWN,                       true, false),
        EXPECTED_RDN_DELIMITER                         (-315, ChaiErrorCode.UNKNOWN,                       true, false),
        TOO_MANY_TOKENS                                (-316, ChaiErrorCode.UNKNOWN,                       true, false),
        INCONSISTENT_MULTIAVA                          (-317, ChaiErrorCode.UNKNOWN,                       true, false),
        COUNTRY_NAME_TOO_LONG                          (-318, ChaiErrorCode.UNKNOWN,                       true, false),
        SYSTEM_ERROR                                   (-319, ChaiErrorCode.UNKNOWN,                       true, false),
        CANT_ADD_ROOT                                  (-320, ChaiErrorCode.UNKNOWN,                       true, false),
        UNABLE_TO_ATTACH                               (-321, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_HANDLE                                 (-322, ChaiErrorCode.UNKNOWN,                       true, false),
        BUFFER_ZERO_LENGTH                             (-323, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_REPLICA_TYPE                           (-324, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_ATTR_SYNTAX                            (-325, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_FILTER_SYNTAX                          (-326, ChaiErrorCode.UNKNOWN,                       true, false),
        CONTEXT_CREATION                               (-328, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_UNION_TAG                              (-329, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_SERVER_RESPONSE                        (-330, ChaiErrorCode.UNKNOWN,                       true, false),
        NULL_POINTER                                   (-331, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SERVER_FOUND                                (-332, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_CONNECTION                                  (-333, ChaiErrorCode.UNKNOWN,                       true, false),
        RDN_TOO_LONG                                   (-334, ChaiErrorCode.UNKNOWN,                       true, false),
        DUPLICATE_TYPE                                 (-335, ChaiErrorCode.UNKNOWN,                       true, false),
        DATA_STORE_FAILURE                             (-336, ChaiErrorCode.UNKNOWN,                       true, false),
        NOT_LOGGED_IN                                  (-337, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_PASSWORD_CHARS                         (-338, ChaiErrorCode.UNKNOWN,                       true, false),
        FAILED_SERVER_AUTHENT                          (-339, ChaiErrorCode.UNKNOWN,                       true, false),
        TRANSPORT                                      (-340, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SUCH_SYNTAX                                 (-341, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_DS_NAME                                (-342, ChaiErrorCode.UNKNOWN,                       true, false),
        ATTR_NAME_TOO_LONG                             (-343, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_TDS                                    (-344, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_DS_VERSION                             (-345, ChaiErrorCode.UNKNOWN,                       true, false),
        UNICODE_TRANSLATION                            (-346, ChaiErrorCode.UNKNOWN,                       true, false),
        SCHEMA_NAME_TOO_LONG                           (-347, ChaiErrorCode.UNKNOWN,                       true, false),
        UNICODE_FILE_NOT_FOUND                         (-348, ChaiErrorCode.UNKNOWN,                       true, false),
        UNICODE_ALREADY_LOADED                         (-349, ChaiErrorCode.UNKNOWN,                       true, false),
        NOT_CONTEXT_OWNER                              (-350, ChaiErrorCode.UNKNOWN,                       true, false),
        ATTEMPT_TO_AUTHENTICATE_0                      (-351, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_WRITABLE_REPLICAS                           (-352, ChaiErrorCode.UNKNOWN,                       true, false),
        DN_TOO_LONG                                    (-353, ChaiErrorCode.UNKNOWN,                       true, false),
        RENAME_NOT_ALLOWED                             (-354, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_NOT_NDS_FOR_NT                             (-355, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_NDS_FOR_NT_NO_DOMAIN                       (-356, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_NDS_FOR_NT_SYNC_DISABLED                   (-357, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_ITR_INVALID_HANDLE                         (-358, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_ITR_INVALID_POSITION                       (-359, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_ITR_INVALID_SEARCH_DATA                    (-360, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_ITR_INVALID_SCOPE                          (-361, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_ITR_MAX_COUNT                              (-362, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_ALREADY_LOADED                             (-489, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_FUTURE_OPCODE                              (-490, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_NO_SUCH_FILE                               (-491, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_TOO_MANY_FILES                             (-492, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_NO_PERMISSION                              (-493, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_NO_MEMORY                                  (-494, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_LOAD_FAILED                                (-495, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_HANDLE_BAD                                 (-496, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_HANDLE_MISMATCH                            (-497, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_RULES_CORRUPT                              (-498, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_NO_DEFAULT                                 (-499, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_INSUFFICIENT_BUFFER                        (-500, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_OPEN_FAILED                                (-501, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_NO_LOAD_DIR                                (-502, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_BAD_FILE_HANDLE                            (-503, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_READ_FAILED                                (-504, ChaiErrorCode.UNKNOWN,                       true, false),
        UNI_TRANS_CORRUPT                              (-505, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SUCH_ENTRY                                  (-601, ChaiErrorCode.NO_SUCH_ENTRY,                 true, false),
        NO_SUCH_VALUE                                  (-602, ChaiErrorCode.NO_SUCH_VALUE,                 true, false),
        NO_SUCH_ATTRIBUTE                              (-603, ChaiErrorCode.NO_SUCH_ATTRIBUTE,             true, false),
        NO_SUCH_CLASS                                  (-604, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SUCH_PARTITION                              (-605, ChaiErrorCode.UNKNOWN,                       true, false),
        ENTRY_ALREADY_EXISTS                           (-606, ChaiErrorCode.UNKNOWN,                       true, false),
        NOT_EFFECTIVE_CLASS                            (-607, ChaiErrorCode.UNKNOWN,                       true, false),
        ILLEGAL_ATTRIBUTE                              (-608, ChaiErrorCode.UNKNOWN,                       true, false),
        MISSING_MANDATORY                              (-609, ChaiErrorCode.UNKNOWN,                       true, false),
        ILLEGAL_DS_NAME                                (-610, ChaiErrorCode.UNKNOWN,                       true, false),
        ILLEGAL_CONTAINMENT                            (-611, ChaiErrorCode.UNKNOWN,                       true, false),
        CANT_HAVE_MULTIPLE_VALUES                      (-612, ChaiErrorCode.UNKNOWN,                       true, false),
        SYNTAX_VIOLATION                               (-613, ChaiErrorCode.UNKNOWN,                       true, false),
        DUPLICATE_VALUE                                (-614, ChaiErrorCode.UNKNOWN,                       true, false),
        ATTRIBUTE_ALREADY_EXISTS                       (-615, ChaiErrorCode.UNKNOWN,                       true, false),
        MAXIMUM_ENTRIES_EXIST                          (-616, ChaiErrorCode.UNKNOWN,                       true, false),
        DATABASE_FORMAT                                (-617, ChaiErrorCode.UNKNOWN,                       true, false),
        INCONSISTENT_DATABASE                          (-618, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_COMPARISON                             (-619, ChaiErrorCode.UNKNOWN,                       true, false),
        COMPARISON_FAILED                              (-620, ChaiErrorCode.UNKNOWN,                       true, false),
        TRANSACTIONS_DISABLED                          (-621, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_TRANSPORT                              (-622, ChaiErrorCode.UNKNOWN,                       true, false),
        SYNTAX_INVALID_IN_NAME                         (-623, ChaiErrorCode.UNKNOWN,                       true, false),
        REPLICA_ALREADY_EXISTS                         (-624, ChaiErrorCode.UNKNOWN,                       true, false),
        TRANSPORT_FAILURE                              (-625, ChaiErrorCode.UNKNOWN,                       true, false),
        ALL_REFERRALS_FAILED                           (-626, ChaiErrorCode.UNKNOWN,                       true, false),
        CANT_REMOVE_NAMING_VALUE                       (-627, ChaiErrorCode.UNKNOWN,                       true, false),
        OBJECT_CLASS_VIOLATION                         (-628, ChaiErrorCode.UNKNOWN,                       true, false),
        ENTRY_IS_NOT_LEAF                              (-629, ChaiErrorCode.UNKNOWN,                       true, false),
        DIFFERENT_TREE                                 (-630, ChaiErrorCode.UNKNOWN,                       true, false),
        ILLEGAL_REPLICA_TYPE                           (-631, ChaiErrorCode.UNKNOWN,                       true, false),
        SYSTEM_FAILURE                                 (-632, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_ENTRY_FOR_ROOT                         (-633, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_REFERRALS                                   (-634, ChaiErrorCode.UNKNOWN,                       true, false),
        REMOTE_FAILURE                                 (-635, ChaiErrorCode.UNKNOWN,                       true, false),
        UNREACHABLE_SERVER                             (-636, ChaiErrorCode.UNKNOWN,                       true, false),
        PREVIOUS_MOVE_IN_PROGRESS                      (-637, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_CHARACTER_MAPPING                           (-638, ChaiErrorCode.UNKNOWN,                       true, false),
        INCOMPLETE_AUTHENTICATION                      (-639, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_CERTIFICATE                            (-640, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_REQUEST                                (-641, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_ITERATION                              (-642, ChaiErrorCode.UNKNOWN,                       true, false),
        SCHEMA_IS_NONREMOVABLE                         (-643, ChaiErrorCode.UNKNOWN,                       true, false),
        SCHEMA_IS_IN_USE                               (-644, ChaiErrorCode.UNKNOWN,                       true, false),
        CLASS_ALREADY_EXISTS                           (-645, ChaiErrorCode.UNKNOWN,                       true, false),
        BAD_NAMING_ATTRIBUTES                          (-646, ChaiErrorCode.UNKNOWN,                       true, false),
        NOT_ROOT_PARTITION                             (-647, ChaiErrorCode.UNKNOWN,                       true, false),
        INSUFFICIENT_STACK                             (-648, ChaiErrorCode.UNKNOWN,                       true, false),
        INSUFFICIENT_BUFFER                            (-649, ChaiErrorCode.UNKNOWN,                       true, false),
        AMBIGUOUS_CONTAINMENT                          (-650, ChaiErrorCode.UNKNOWN,                       true, false),
        AMBIGUOUS_NAMING                               (-651, ChaiErrorCode.UNKNOWN,                       true, false),
        DUPLICATE_MANDATORY                            (-652, ChaiErrorCode.UNKNOWN,                       true, false),
        DUPLICATE_OPTIONAL                             (-653, ChaiErrorCode.UNKNOWN,                       true, false),
        PARTITION_BUSY                                 (-654, ChaiErrorCode.UNKNOWN,                       true, false),
        MULTIPLE_REPLICAS                              (-655, ChaiErrorCode.UNKNOWN,                       true, false),
        CRUCIAL_REPLICA                                (-656, ChaiErrorCode.UNKNOWN,                       true, false),
        SCHEMA_SYNC_IN_PROGRESS                        (-657, ChaiErrorCode.UNKNOWN,                       true, false),
        SKULK_IN_PROGRESS                              (-658, ChaiErrorCode.UNKNOWN,                       true, false),
        TIME_NOT_SYNCHRONIZED                          (-659, ChaiErrorCode.UNKNOWN,                       true, false),
        RECORD_IN_USE                                  (-660, ChaiErrorCode.UNKNOWN,                       true, false),
        DS_VOLUME_NOT_MOUNTED                          (-661, ChaiErrorCode.UNKNOWN,                       true, false),
        DS_VOLUME_IO_FAILURE                           (-662, ChaiErrorCode.UNKNOWN,                       true, false),
        DS_LOCKED                                      (-663, ChaiErrorCode.UNKNOWN,                       false, false),
        OLD_EPOCH                                      (-664, ChaiErrorCode.UNKNOWN,                       true, false),
        NEW_EPOCH                                      (-665, ChaiErrorCode.UNKNOWN,                       true, false),
        INCOMPATIBLE_DS_VERSION                        (-666, ChaiErrorCode.UNKNOWN,                       true, false),
        PARTITION_ROOT                                 (-667, ChaiErrorCode.UNKNOWN,                       true, false),
        ENTRY_NOT_CONTAINER                            (-668, ChaiErrorCode.UNKNOWN,                       true, false),
        FAILED_AUTHENTICATION                          (-669, ChaiErrorCode.FAILED_AUTHENTICATION,         true, true),
        INVALID_CONTEXT                                (-670, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SUCH_PARENT                                 (-671, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_ACCESS                                      (-672, ChaiErrorCode.NO_ACCESS,                     true, false),
        REPLICA_NOT_ON                                 (-673, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_NAME_SERVICE                           (-674, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_TASK                                   (-675, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_CONN_HANDLE                            (-676, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_IDENTITY                               (-677, ChaiErrorCode.UNKNOWN,                       true, false),
        DUPLICATE_ACL                                  (-678, ChaiErrorCode.UNKNOWN,                       true, false),
        PARTITION_ALREADY_EXISTS                       (-679, ChaiErrorCode.UNKNOWN,                       true, false),
        TRANSPORT_MODIFIED                             (-680, ChaiErrorCode.UNKNOWN,                       true, false),
        ALIAS_OF_AN_ALIAS                              (-681, ChaiErrorCode.UNKNOWN,                       true, false),
        AUDITING_FAILED                                (-682, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_API_VERSION                            (-683, ChaiErrorCode.UNKNOWN,                       true, false),
        SECURE_NCP_VIOLATION                           (-684, ChaiErrorCode.UNKNOWN,                       true, false),
        MOVE_IN_PROGRESS                               (-685, ChaiErrorCode.UNKNOWN,                       true, false),
        NOT_LEAF_PARTITION                             (-686, ChaiErrorCode.UNKNOWN,                       true, false),
        CANNOT_ABORT                                   (-687, ChaiErrorCode.UNKNOWN,                       true, false),
        CACHE_OVERFLOW                                 (-688, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_SUBORDINATE_COUNT                      (-689, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_RDN                                    (-690, ChaiErrorCode.UNKNOWN,                       true, false),
        MOD_TIME_NOT_CURRENT                           (-691, ChaiErrorCode.UNKNOWN,                       true, false),
        INCORRECT_BASE_CLASS                           (-692, ChaiErrorCode.UNKNOWN,                       true, false),
        MISSING_REFERENCE                              (-693, ChaiErrorCode.UNKNOWN,                       true, false),
        LOST_ENTRY                                     (-694, ChaiErrorCode.UNKNOWN,                       true, false),
        AGENT_ALREADY_REGISTERED                       (-695, ChaiErrorCode.UNKNOWN,                       true, false),
        DS_LOADER_BUSY                                 (-696, ChaiErrorCode.UNKNOWN,                       true, false),
        DS_CANNOT_RELOAD                               (-697, ChaiErrorCode.UNKNOWN,                       true, false),
        REPLICA_IN_SKULK                               (-698, ChaiErrorCode.UNKNOWN,                       true, false),
        FATAL_ERR                                      (-699, ChaiErrorCode.UNKNOWN,                       true, false),
        OBSOLETE_API                                   (-700, ChaiErrorCode.UNKNOWN,                       true, false),
        SYNCHRONIZATION_DISABLED                       (-701, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_PARAMETER                              (-702, ChaiErrorCode.UNKNOWN,                       true, false),
        DUPLICATE_TEMPLATE                             (-703, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_MASTER_REPLICA                              (-704, ChaiErrorCode.UNKNOWN,                       true, false),
        DUPLICATE_CONTAINMENT                          (-705, ChaiErrorCode.UNKNOWN,                       true, false),
        NOT_SIBLING                                    (-706, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_SIGNATURE                              (-707, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_RESPONSE                               (-708, ChaiErrorCode.UNKNOWN,                       true, false),
        INSUFFICIENT_SOCKETS                           (-709, ChaiErrorCode.UNKNOWN,                       true, false),
        DATABASE_READ_FAIL                             (-710, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_CODE_PAGE                              (-711, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_ESCAPE_CHAR                            (-712, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_DELIMITERS                             (-713, ChaiErrorCode.UNKNOWN,                       true, false),
        NOT_IMPLEMENTED                                (-714, ChaiErrorCode.UNKNOWN,                       true, false),
        CHECKSUM_FAILURE                               (-715, ChaiErrorCode.UNKNOWN,                       true, false),
        CHECKSUMMING_NOT_SUPPORTED                     (-716, ChaiErrorCode.UNKNOWN,                       true, false),
        CRC_FAILURE                                    (-717, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_ENTRY_HANDLE                           (-718, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_VALUE_HANDLE                           (-719, ChaiErrorCode.UNKNOWN,                       true, false),
        CONNECTION_DENIED                              (-720, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SUCH_FEDERATION_LINK                        (-721, ChaiErrorCode.UNKNOWN,                       true, false),
        OP_SCHEMA_MISMATCH                             (-722, ChaiErrorCode.UNKNOWN,                       true, false),
        STREAM_NOT_FOUND                               (-723, ChaiErrorCode.UNKNOWN,                       true, false),
        DCLIENT_UNAVAILABLE                            (-724, ChaiErrorCode.UNKNOWN,                       true, false),
        MASV_NO_ACCESS                                 (-725, ChaiErrorCode.UNKNOWN,                       true, false),
        MASV_INVALID_REQUEST                           (-726, ChaiErrorCode.UNKNOWN,                       true, false),
        MASV_FAILURE                                   (-727, ChaiErrorCode.UNKNOWN,                       true, false),
        MASV_ALREADY_EXISTS                            (-728, ChaiErrorCode.UNKNOWN,                       true, false),
        MASV_NOT_FOUND                                 (-729, ChaiErrorCode.UNKNOWN,                       true, false),
        MASV_BAD_RANGE                                 (-730, ChaiErrorCode.UNKNOWN,                       true, false),
        VALUE_DATA                                     (-731, ChaiErrorCode.UNKNOWN,                       true, false),
        DATABASE_LOCKED                                (-732, ChaiErrorCode.UNKNOWN,                       true, false),
        DATABASE_ALREADY_EXISTS                        (-733, ChaiErrorCode.UNKNOWN,                       true, false),
        DATABASE_NOT_FOUND                             (-734, ChaiErrorCode.UNKNOWN,                       true, false),
        NOTHING_TO_ABORT                               (-735, ChaiErrorCode.UNKNOWN,                       true, false),
        END_OF_STREAM                                  (-736, ChaiErrorCode.UNKNOWN,                       true, false),
        NO_SUCH_TEMPLATE                               (-737, ChaiErrorCode.UNKNOWN,                       true, false),
        SAS_LOCKED                                     (-738, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_SAS_VERSION                            (-739, ChaiErrorCode.UNKNOWN,                       true, false),
        SAS_ALREADY_REGISTERED                         (-740, ChaiErrorCode.UNKNOWN,                       true, false),
        NAME_TYPE_NOT_SUPPORTED                        (-741, ChaiErrorCode.UNKNOWN,                       true, false),
        WRONG_DS_VERSION                               (-742, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_CONTROL_FUNCTION                       (-743, ChaiErrorCode.UNKNOWN,                       true, false),
        INVALID_CONTROL_STATE                          (-744, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_CACHE_IN_USE                               (-745, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_ZERO_CREATION_TIME                         (-746, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_WOULD_BLOCK                                (-747, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_CONN_TIMEOUT                               (-748, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_TOO_MANY_REFERRALS                         (-749, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_OPERATION_CANCELLED                        (-750, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_UNKNOWN_TARGET                             (-751, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_GUID_FAILURE                               (-752, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_INCOMPATIBLE_OS                            (-753, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_CALLBACK_CANCEL                            (-754, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_INVALID_SYNC_DATA                          (-755, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_STREAM_EXISTS                              (-756, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_AUXILIARY_HAS_CONTAINMENT                  (-757, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_AUXILIARY_NOT_CONTAINER                    (-758, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_AUXILIARY_NOT_EFFECTIVE                    (-759, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_AUXILIARY_ON_ALIAS                         (-760, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_HAVE_SEEN_STATE                            (-761, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_VERB_LOCKED                                (-762, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_VERB_EXCEEDS_TABLE_LENGTH                  (-763, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_BOF_HIT                                    (-764, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_EOF_HIT                                    (-765, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_INCOMPATIBLE_REPLICA_VER                   (-766, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_QUERY_TIMEOUT                              (-767, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_QUERY_MAX_COUNT                            (-768, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_DUPLICATE_NAMING                           (-769, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_NO_TRANS_ACTIVE                            (-770, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_TRANS_ACTIVE                               (-771, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_ILLEGAL_TRANS_OP                           (-772, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_ITERATOR_SYNTAX                            (-773, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_REPAIRING_DIB                              (-774, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_INVALID_OID_FORMAT                         (-775, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_DS_AGENT_CLOSING                           (-776, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_SPARSE_FILTER_VIOLATION                    (-777, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_VPVECTOR_CORRELATION_ERR                   (-778, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_CANNOT_GO_REMOTE                           (-779, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_REQUEST_NOT_SUPPORTED                      (-780, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_ENTRY_NOT_LOCAL                            (-781, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_ROOT_UNREACHABLE                           (-782, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_VRDIM_NOT_INITIALIZED                      (-783, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_WAIT_TIMEOUT                               (-784, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_DIB_ERROR                                  (-785, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_DIB_IO_FAILURE                             (-786, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_ILLEGAL_SCHEMA_ATTRIBUTE                   (-787, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_SCHEMA_PARTITION                           (-788, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_INVALID_TEMPLATE                           (-789, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_OPENING_FILE                               (-790, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_DIRECT_OPENING_FILE                        (-791, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_CREATING_FILE                              (-792, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_DIRECT_CREATING_FILE                       (-793, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_READING_FILE                               (-794, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_DIRECT_READING_FILE                        (-795, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_WRITING_FILE                               (-796, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_DIRECT_WRITING_FILE                        (-797, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_POSITIONING_IN_FILE                        (-798, ChaiErrorCode.UNKNOWN,                       true, false),
        ERR_GETTING_FILE_SIZE                          (-799, ChaiErrorCode.UNKNOWN,                       true, false),

        UNSUPPORTED_OPERATION                          (0,   ChaiErrorCode.UNSUPPORTED_OPERATION, true, false, "Unrecognized extended operation"),

        ;

        private int errorCodeNumber;
        private ChaiErrorCode chaiErrorCode;
        private boolean permenant;
        private boolean authentication;
        private String[] errorStrings;

        EdirError(
                final int errorCodeNumber,
                final ChaiErrorCode chaiErrorCode,
                final boolean permenant,
                final boolean authentication,
                final String... errorStrings
        )
        {
            this.errorCodeNumber = errorCodeNumber;
            this.chaiErrorCode = chaiErrorCode;
            this.permenant = permenant;
            this.authentication = authentication;
            this.errorStrings = errorStrings;
        }

        public int getErrorCodeNumber()
        {
            return errorCodeNumber;
        }

        public boolean isPermenant()
        {
            return permenant;
        }

        public boolean isAuthentication()
        {
            return authentication;
        }

        public ChaiErrorCode getChaiErrorCode()
        {
            return chaiErrorCode;
        }

        public String[] getErrorStrings()
        {
            return errorStrings;
        }
    }
}
